service: chartsy-api

#point to env file/s for env vars
useDotenv: true

#ensure serverless framework version is specified for consistency (not grabbing latest version with unpredictable results)
frameworkVersion: '3'

# cloud services provider config
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  deploymentBucket:
    name: serverless-framework-deployments-eu-west-2-4503d36b-608c
  environment:
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    target: node20
    exclude:
      - aws-sdk
    external: []