-- Collections table
CREATE TABLE IF NOT EXISTS collections (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_name VARCHAR NOT NULL,
  icon            VARCHAR,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Items table (belongs to a collection)
CREATE TABLE IF NOT EXISTS items (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id   INT NOT NULL,
  item_name       VARCHAR NOT NULL,
  icon            VARCHAR,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Item Data table (data entries for an item)
CREATE TABLE IF NOT EXISTS item_data (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id         INT NOT NULL,
  data_type       VARCHAR NOT NULL DEFAULT 'text',  -- extensible beyond text later
  data_body            TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);